# Generated by Django 4.2.3 on 2023-08-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_postalcode_shippingaddress_postalcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="qty",
            field=models.IntegerField(default=0),
        ),
    ]
