# Generated by Django 4.2.3 on 2023-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_orderitem_qty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="totalPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="qty",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
