# Generated by Django 4.2.3 on 2023-08-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_order_totalprice_alter_orderitem_qty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="qty",
        ),
    ]
