# Generated by Django 4.2.3 on 2023-08-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_shippingaddress_qty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="isDelivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="paidAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
