const products = [
  
    {
        '_id': "1",
        'name':'Mango',
        'image':'/images/ps4.jpeg',
        'description':'Ekdom fresh from Kola Bagan',
        'price':130,
        'countInStock':0,
        'rating':4.2,
        'numReviews':24,
    },
    {
        '_id': "2",
        'name':'Grape',
        'image':'/images/ps4.jpeg',
        'description':'Ekdom grape fresh from Kola Bagan',
        'price':160,
        'countInStock':12,
        'rating':4.5,
        'numReviews':13,
    },
    {
        '_id': "3",
        'name':'Mango',
        'image':'/images/ps4.jpeg',
        'description':'Ekdom fresh from Kola Bagan',
        'price':130,
        'countInStock':'40Kg',
        'rating':4.2,
        'numReviews':24,
    },
    {
        '_id': "4",
        'name':'Grape',
        'image':'/images/ps4.jpeg',
        'description':'Ekdom grape fresh from Kola Bagan',
        'price':110,
        'countInStock':15,
        'rating':4.5,
        'numReviews':13,
    },
    {
        '_id': "5",
        'name':'Mango3',
        'image':'/images/ps4.jpeg',
        'description':'Ekdom fresh from Kola Bagan',
        'price':120,
        'countInStock':34,
        'rating':4.2,
        'numReviews':24,
    },
    {
        '_id': "6",
        'name':'Grape3',
        'image':'/images/ps4.jpeg',
        'description':'Ekdom grape fresh from Kola Bagan',
        'price':150,
        'countInStock':12,
        'rating':4.5,
        'numReviews':13,
    },
    {
        '_id': "7",
        'name':'Mango6',
        'image':'/images/ps4.jpeg',
        'description':'Ekdom fresh from Kola Bagan',
        'price':105,
        'countInStock':21,
        'rating':4.2,
        'numReviews':24,
    },
    {
        '_id': "8",
        'name':'Grape4',
        'image':'/images/ps4.jpeg',
        'description':'Ekdom grape fresh from Kola Bagan',
        'price':105,
        'countInStock':10,
        'rating':4.5,
        'numReviews':13,
    },

]

export default products